version: '3.1'

services:
  flowise:
    image: flowiseai/flowise:latest
    restart: always
    environment:
        - PORT=${FLOWISE_PORT:-3000}
        - TOOL_FUNCTION_BUILTIN_DEP=fs,path
    ports:
        - '${FLOWISE_PORT:-3000}:3000'
    volumes:
        - ~/.flowise:/root/.flowise
        - ./documentos:/data/documentos
        - ./data:/data/csvs
    extra_hosts:
      - "host.docker.internal:host-gateway"
